// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1EvmABi7o-rTgHtHgu4c_In6PnenHg3k',
    appId: '1:664964818182:web:daf149e0c5140e54796a87',
    messagingSenderId: '664964818182',
    projectId: 'flutter-test-749f0',
    authDomain: 'flutter-test-749f0.firebaseapp.com',
    storageBucket: 'flutter-test-749f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMdBcZL44YIrg4pqJi8hkRz9wL49H0t4',
    appId: '1:664964818182:android:8ddd2d9a52909326796a87',
    messagingSenderId: '664964818182',
    projectId: 'flutter-test-749f0',
    storageBucket: 'flutter-test-749f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-nAgJx7TeBmRO33KnQ_iKtQC3qnV7ebA',
    appId: '1:664964818182:ios:eb43d07221d221e7796a87',
    messagingSenderId: '664964818182',
    projectId: 'flutter-test-749f0',
    storageBucket: 'flutter-test-749f0.appspot.com',
    iosClientId: '664964818182-n8kuohj4kj7r0k15rdcfrf9iaihhm2pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-nAgJx7TeBmRO33KnQ_iKtQC3qnV7ebA',
    appId: '1:664964818182:ios:eb43d07221d221e7796a87',
    messagingSenderId: '664964818182',
    projectId: 'flutter-test-749f0',
    storageBucket: 'flutter-test-749f0.appspot.com',
    iosClientId: '664964818182-n8kuohj4kj7r0k15rdcfrf9iaihhm2pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1EvmABi7o-rTgHtHgu4c_In6PnenHg3k',
    appId: '1:664964818182:web:f189aa485f25dcc4796a87',
    messagingSenderId: '664964818182',
    projectId: 'flutter-test-749f0',
    authDomain: 'flutter-test-749f0.firebaseapp.com',
    storageBucket: 'flutter-test-749f0.appspot.com',
  );
}
